version: '3.8'

services:
  # Development service
  react-geo-client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-geo-client-dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    # Optional: Define a network to connect with other services
    networks:
      - react-geo-network

  # Production service
  react-geo-client-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-geo-client-prod
    ports:
      - "80:80"
    # Static assets, no live reloading required
    networks:
      - react-geo-network

networks:
  react-geo-network:
    driver: bridge
